### ISSUE TITLE
Размер шрифта в легенде

### ISSUE THREAD

**Issue by willbasky** [a-chabin/ekaterinburg-plan#2]
Плохо видно номера зон на цветовых плашках в легенде. 
Вожмно ли увеличить?
У меня диагональ экрана 14 дюймов и 2K разрешение.

**Comment by a-chabin** [comment]
> Плохо видно номера зон на цветовых плашках в легенде. Вожмно ли увеличить? У меня диагональ экрана 14 дюймов и 2K разрешение.

Спасибо за обратную связь!
Попробовал увеличить номера зон на картинке с легендой, должно стать [заметнее](map.genplanekb.city).

![image](https://user-images.githubusercontent.com/22644149/137257812-f2966c8e-4611-45cf-9e68-1c149cd925bf.png)

P.S. Возможно, потребуется сбросить кэш

**Comment by willbasky** [comment]
Да, так лучше видно.
![image](https://user-images.githubusercontent.com/28530747/137285674-6268ba4f-4efa-45f6-8d51-f86f4c98126b.png)
